/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package sandbox

import kotlinsandbox.jsonvalidate.EveritOrg
import kotlinsandbox.jsonvalidate.Justify
import kotlinsandbox.jsonvalidate.Medeia
import kotlinsandbox.jsonvalidate.Networknt

class App {
    val greeting: String
        get() {
            return "Hello world."
        }
}

fun main(args: Array<String>) {
//    println(App().greeting)

    println("-".repeat(60))
    println("everit-org:")
    EveritOrg().run()

    println("-".repeat(60))
    println("networknt:")
    Networknt().run()

    println("-".repeat(60))
    println("justify:")
    Justify().run()

    println("-".repeat(60))
    println("medeia:")
    Medeia().run()
}
